@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kihira.minicreatures.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;