@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kihira.minicreatures.client.render;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;