@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kihira.minicreatures.common.personality;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;