@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kihira.minicreatures.common.item;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;