@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kihira.minicreatures.client.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;